# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170902_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
